### ISSUE TITLE
Dictation element cannot handle non-ASCII characters

### ISSUE THREAD

**Issue by t4ngo** [t4ngo/dragonfly#11]
Dragonfly's Dictation element cannot handle non-ASCII characters, such as the last letter in the "touché". The cause of this bug is that Python v2 defaults to ASCII encoding of string objects, whereas Dragon NaturallySpeaking uses the windows-1252 encoding (as stated on the Vocola website here: http://vocola.net/v2/NonEnglish.asp).

This bug can easily be reproduced by including a non-ASCII character in any of dictated element. For example "say touché" for the _multiedit.py command module.

**Comment by chep** [comment]
Hi,

I still have the problem.

When I add this rule:

class ChepTest(MappingRule):
	mapping = {
		'relâche': Text('test'),
	}

I have this error in natlink window:

  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 309, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_chep.py", line 262, in <module>
    grammar.add_rule(ChepTest())
  File "C:\Python27\lib\site-packages\dragonfly\grammar\rule_mapping.py", line 146, in __init__
    c = Compound(spec, elements=self._extras, value=value)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\elements_compound.py", line 273, in __init__
    raise SyntaxError("Invalid compound spec: %r" % spec)
SyntaxError: Invalid compound spec: u'rel\xe2che'

I tried to add
# -*- encoding: windows-1252 -*-
at the beginning of my file (I tried utf8 too).

I also tried
u'relâche': Text('test'),
But nothing worked.

**Comment by seekM** [comment]
I am having the same problem.

**Comment by chep** [comment]
I "solved" it. I think this will only work for french language but I'm not a
python expert so I don't know how to fix it.

string.letters and string.digits functions give a string containing all ASCII
characters. Maybe there is something in python to get all special characters
more efficient than u"éèàùâêîôûäëïöüÉÈÀÙÂÊÎÔÛÄËÏÖÜ".

From 67e2b4a3211816320b6adb204019515a479b6500 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?C=C3=A9dric=20Ch=C3=A9pied?= <cedric.chepied@gmail.com>
Date: Tue, 23 Aug 2016 10:23:28 +0200
Subject: [PATCH 1/2] Fix encoding bug

---
 dragonfly/engines/backend_natlink/compiler.py | 2 +-
 dragonfly/grammar/elements_compound.py        | 8 +++++---
 2 files changed, 6 insertions(+), 4 deletions(-)

diff --git a/dragonfly/engines/backend_natlink/compiler.py b/dragonfly/engines/backend_natlink/compiler.py
index b30d54e..20db7b6 100644
--- a/dragonfly/engines/backend_natlink/compiler.py
+++ b/dragonfly/engines/backend_natlink/compiler.py
@@ -359,7 +359,7 @@ class _Compiler(object):
             #  characters, so that its size in bytes is a multiple of 4.
             padded_len = (len(name) + 4) & (~3)
             element = struct.pack("LL%ds" % padded_len,
-                padded_len + 8, id, str(name))
+                                  padded_len + 8, id, name.encode('windows-1252'))
             elements.append(element)
 
         # Concatenate all the elements.
diff --git a/dragonfly/grammar/elements_compound.py b/dragonfly/grammar/elements_compound.py
index e875251..29c4129 100644
--- a/dragonfly/grammar/elements_compound.py
+++ b/dragonfly/grammar/elements_compound.py
@@ -1,3 +1,5 @@
+#!/usr/bin/env python
+# -*- encoding: utf-8 -*-
 #
 # This file is part of Dragonfly.
 # (c) Copyright 2007, 2008 by Christo Butcher
@@ -130,7 +132,7 @@ class _Single(parser_.Sequence):
 class _ElementRef(parser_.Sequence):
 
     def __init__(self):
-        characters = string.letters + string.digits + "_"
+        characters = string.letters + string.digits + u"_" + u"éèàâêùôöëäïüû"
         name = parser_.CharacterSeries(characters)
         elements = (parser_.String("<"), name, parser_.String(">"))
         parser_.Sequence.__init__(self, elements)
@@ -154,7 +156,7 @@ class _ElementRef(parser_.Sequence):
 class _ActionRef(parser_.Sequence):
 
     def __init__(self):
-        characters = string.letters + string.digits + "_"
+        characters = string.letters + string.digits + "_"  + u"éèàâêùôöëäïüû"
         name = parser_.CharacterSeries(characters)
         elements = (parser_.String("{"), name, parser_.String("}"))
         parser_.Sequence.__init__(self, elements)
@@ -178,7 +180,7 @@ class _ActionRef(parser_.Sequence):
 class _Literal(parser_.Sequence):
 
     def __init__(self):
-        characters = string.letters + string.digits + "_-.'"
+        characters = string.letters + string.digits + "_-.'" + u"éèàâêùôöëäïüû"
         word = parser_.CharacterSeries(characters)
         whitespace = parser_.Whitespace()
         elements = (
-- 
2.9.3

From f01f1127efa8aa95cee3a2e2b77f5267584049a2 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?C=C3=A9dric=20Ch=C3=A9pied?= <cedric.chepied@gmail.com>
Date: Wed, 24 Aug 2016 11:03:45 +0200
Subject: [PATCH 2/2] Fix encoding fix

---
 dragonfly/grammar/elements_compound.py | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/dragonfly/grammar/elements_compound.py b/dragonfly/grammar/elements_compound.py
index 29c4129..1760f37 100644
--- a/dragonfly/grammar/elements_compound.py
+++ b/dragonfly/grammar/elements_compound.py
@@ -132,7 +132,7 @@ class _Single(parser_.Sequence):
 class _ElementRef(parser_.Sequence):
 
     def __init__(self):
-        characters = string.letters + string.digits + u"_" + u"éèàâêùôöëäïüû"
+        characters = string.letters + string.digits + u"_" + u"éèàùâêîôûäëïöüÉÈÀÙÂÊÎÔÛÄËÏÖÜ"
         name = parser_.CharacterSeries(characters)
         elements = (parser_.String("<"), name, parser_.String(">"))
         parser_.Sequence.__init__(self, elements)
@@ -156,7 +156,7 @@ class _ElementRef(parser_.Sequence):
 class _ActionRef(parser_.Sequence):
 
     def __init__(self):
-        characters = string.letters + string.digits + "_"  + u"éèàâêùôöëäïüû"
+        characters = string.letters + string.digits + "_"  + u"éèàùâêîôûäëïöüÉÈÀÙÂÊÎÔÛÄËÏÖÜ"
         name = parser_.CharacterSeries(characters)
         elements = (parser_.String("{"), name, parser_.String("}"))
         parser_.Sequence.__init__(self, elements)
@@ -180,7 +180,7 @@ class _ActionRef(parser_.Sequence):
 class _Literal(parser_.Sequence):
 
     def __init__(self):
-        characters = string.letters + string.digits + "_-.'" + u"éèàâêùôöëäïüû"
+        characters = string.letters + string.digits + "_-.'" + u"éèàùâêîôûäëïöüÉÈÀÙÂÊÎÔÛÄËÏÖÜ"
         word = parser_.CharacterSeries(characters)
         whitespace = parser_.Whitespace()
         elements = (
-- 
2.9.3

**Comment by chep** [comment]
My rules are created like this:
`u'relâche': Text(u'test'),`
And it works.

**Comment by seekM** [comment]
Thanks a lot! This is helping me a lot, really.

I tried something similar: I added
```
print(locale.getlocale())
print(string.letters)
```
at the top of my rules' file and got
```
(None, None)
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
```
So I added 
```locale.setlocale(locale.LC_ALL, '')``` 
([documentation#1](https://docs.python.org/2/library/string.html#string.letters), [documentation#2](https://docs.python.org/3/library/locale.html#locale.setlocale))
to my rules' file as well which yielded
```
('de_DE', 'cp1252')
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸªµºÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ
```
but it still did not work. Maybe it should have been inserted at a different place?

**Comment by chep** [comment]
`locale.setlocale(locale.LC_ALL, '')`
did the job.

This patch seems to work. I don't know if this is the right place to set the
locale variable. I'm currently testing, still no bug.
```

From 61602ec65b2d0197391b6e8f3302d7684c91d7db Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?C=C3=A9dric=20Ch=C3=A9pied?= <cedric.chepied@gmail.com>
Date: Fri, 16 Sep 2016 08:13:51 +0200
Subject: [PATCH] Better correction for encoding

---
 dragonfly/grammar/elements_compound.py | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)

diff --git a/dragonfly/grammar/elements_compound.py b/dragonfly/grammar/elements_compound.py
index 1760f37..e9d2b67 100644
--- a/dragonfly/grammar/elements_compound.py
+++ b/dragonfly/grammar/elements_compound.py
@@ -34,6 +34,7 @@ import string
 import dragonfly.grammar.elements_basic as elements_
 import dragonfly.parser as parser_
 import logging
+import locale
 
 
 class _Stuff(parser_.Sequence):
@@ -132,7 +133,8 @@ class _Single(parser_.Sequence):
 class _ElementRef(parser_.Sequence):
 
     def __init__(self):
-        characters = string.letters + string.digits + "_"
+        locale.setlocale(locale.LC_ALL, '')
+        characters = unicode(string.letters + string.digits + "_", "windows-1252")
         name = parser_.CharacterSeries(characters)
         elements = (parser_.String("<"), name, parser_.String(">"))
         parser_.Sequence.__init__(self, elements)
@@ -156,7 +158,8 @@ class _ElementRef(parser_.Sequence):
 class _ActionRef(parser_.Sequence):
 
     def __init__(self):
-        characters = string.letters + string.digits + "_"
+        locale.setlocale(locale.LC_ALL, '')
+        characters = unicode(string.letters + string.digits + "_", "windows-1252")
         name = parser_.CharacterSeries(characters)
         elements = (parser_.String("{"), name, parser_.String("}"))
         parser_.Sequence.__init__(self, elements)
@@ -180,7 +183,7 @@ class _ActionRef(parser_.Sequence):
 class _Literal(parser_.Sequence):
 
     def __init__(self):
-        characters = string.letters + string.digits + "_-.'"
+        characters = unicode(string.letters + string.digits + "_-.'", "windows-1252")
         word = parser_.CharacterSeries(characters)
         whitespace = parser_.Whitespace()
         elements = (
-- 
2.9.3

```
