### ISSUE TITLE
Won't install with the latest version of python

### ISSUE THREAD

**Issue by jleaders** [t4ngo/dragonfly#32]
pip install dragonfly

On Python 3.4 fails.

**Comment by synkarius** [comment]
I don't think Python 3.x is supported. The PyPI site says that Dragonfly is for Python 2.5. I'm running it on Python 2.7.9.

**Comment by t4ngo** [comment]
Dragonfly currently only supports Python 2.x.

For Dragon NaturallySpeaking users this limitation is also imposed by Natlink, which is only available for Python 2.x.
