### ISSUE TITLE
Identical lists disallowed in ListRefs even when empty (fix suggested)

### ISSUE THREAD

**Issue by jgarvin** [t4ngo/dragonfly#36]
There's a bug preventing adding multiple Lists that are the same value to a grammar. Inside add_list in grammar_base.py there is a check to prevent adding duplicate Lists to a grammar:

        elif lst in self._lists:
            return

I think what this is *intended* to do is prevent you from accidentally adding the same List twice, perhaps by having two ListRefs referring to the same List. However it's followed by another check:

        elif [True for l in self._lists if l.name == lst.name]:
            raise GrammarError("Two lists with the same name '%s' not"
                "allowed." % lst.name)

This check accomplishes the same thing. So what's the difference? Well, the first check is going to check object equality (\_\_eq\_\_) rather than just the name attribute. Lists are defined to inherit the builtin list type, which uses element-wise checking to determine equality, and List doesn't override this behavior, so the name attribute is actually ignored. This means that if you add two separate Lists via two separate ListRefs to a grammar and they happen to have the same value at the time you load the containing rule, they never get added to the grammar.

In my case my rule had two lists, both initially empty because they would later get dynamically updated to have some contents. But because of the first check, only one of the lists would get loaded. When I would update the second list, Dragon would never pick it up, because if add_list returns in the first check then the _grammar member of the List is never set, so any updates to the List object don't propogate up to Natlink. If I manually set the _grammar member myself, when I update the List dragonfly will throw an exception in update_list, saying that the list is not loaded into the grammar because the grammar's _list member was never filled with the List object either.

As I understand it the whole point of Lists in dragonfly is that they are dynamically update-able without needing to reload their containing grammar. Since they're dynamic there's no reason circumstances can't arise that happen to cause two lists at the time the grammar is loaded to happen to have the same value, and it's harmless for them to as long as they're distinct instances with distinct names. **So I think the fix is just to completely remove the first check.**

**As a workaround**, users that don't want to patch their dragonfly install could just before they load their rule load all their lists with temporary unique values then set them back after.

**Comment by jgarvin** [comment]
Excellent, thanks!

**Comment by t4ngo** [comment]
Note that the fix in 6246a4d did uncover a problem into Integer element construction, fixed subsequently in 6c89bcbabe7d98636bdcaebefb977bfac657d855.
