### ISSUE TITLE
Meaning/significance of imported/exported?

### ISSUE THREAD

**Issue by jgarvin** [t4ngo/dragonfly#39]
Short version: When should I set exported/imported on Rule objects to True/False? What difference does it make to Dragon/WSR?

It's not clear to me from the docs what it means for a Rule object to be imported or exported. The description for exported says top level voice commands, so I assume this is as opposed to rules that are only brought in by RuleRef? The description for imported says "if the rule is imported outside its grammar" -- does that mean you need to set it to true for rules being used in multiple grammars or something else?

Also I noticed MappingRule only takes exported. Is there a reason it never makes sense for it to be imported?

I stumbled on these questions trying to figure out why MappingRule construction is slow, so if it can help with that I'm especially keen ;)

**Comment by t4ngo** [comment]
The new documentation on exported and imported rules, added in the commit above, is available online here:
http://dragonfly.readthedocs.org/en/latest/object_model.html#rules

**Comment by jgarvin** [comment]
@t4ngo that helps a lot! I was definitely getting confused by the language suggesting rules could be imported across grammars, makes a lot more sense now that I understand WSR supports it but Dragon doesn't.
