### ISSUE TITLE
Is there a way to remove a rule that has been previously added?

### ISSUE THREAD

**Issue by reckoner** [t4ngo/dragonfly#65]
There is a 

    grammar.add_rule

Is there something like a

    grammar.remove_rule

to remove a rule that had previously been added?

**Comment by tylercal** [comment]
What I use is `rule.disable()` on the rule itself, you can also `grammar.unload()`.

If you really want to remove a rule, the exact method you mentioned does exist:
https://github.com/t4ngo/dragonfly/blob/master/dragonfly/grammar/grammar_base.py#L175
