### ISSUE TITLE
Natlink.getWordInfo broken in DNS v11 and later

### ISSUE THREAD

**Issue by jgarvin** [t4ngo/dragonfly#9]
I ran into the same problem described here, using DNS12: https://groups.google.com/forum/#!topic/dragonflyspeech/P5xYn6C7RXk

If you say "hello cap world" instead of getting "hello World" as the natlink dictation unit test seems to indicate is expected, you will get "hello \cap world". It appears that getWordInfo is either deprecated or broken, and always returns 8 (flag for 'undeletable'), and the codes appear in the text stream now. In a couple days might have a chance to change dragonfly to interpret these but it's possible this is a bug in Natlink.

**Comment by t4ngo** [comment]
I've added support for DNS v11 and higher in the feature/dict-fmt branch, merged into master in commit 87a0a0f56b51bdd4b942fa069bee176fd5013834.

The changes can be viewed here:
http://github.com/t4ngo/dragonfly/compare/4842eab3...87a0a0f5
